import type { Metadata } from "next";
import "../lib/globals.css";
import React from "react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { red_hat_display } from "@/lib/fonts";
import { ThemeToggle } from "@/components/ui/ThemeToggle";
import { GoogleAnalytics } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${red_hat_display.className}`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ThemeToggle />
        </ThemeProvider>
        <GoogleAnalytics gaId="G-0W6D42PTMZ" />
      </body>
    </html>
  );
}
