import { Language } from "@/lib/store";

export const LANGUAGES: Language[] = [
  {
    code: "US",
    name: "US English",
    locale: "en-US",
  },
  {
    code: "GB",
    name: "British English",
    locale: "en-GB",
  },
  { code: "DE", name: "German", locale: "de" },
  { code: "IT", name: "Italian", locale: "it" },
  { code: "FR", name: "French", locale: "fr" },
  { code: "ES", name: "Spanish", locale: "es" },
  { code: "PT", name: "Portuguese", locale: "pt" },
  { code: "NL", name: "Dutch", locale: "nl" },
  { code: "SV", name: "Swedish", locale: "sv" },
  { code: "PL", name: "Polish", locale: "pl" },
  { code: "HR", name: "Croatian", locale: "hr" },
  { code: "DK", name: "Danish", locale: "da" },
  { code: "NO", name: "Norwegian", locale: "no" },
  { code: "FI", name: "Finnish", locale: "fi" },
  { code: "BG", name: "Bulgarian", locale: "bg" },
  { code: "HU", name: "Hungarian", locale: "hu" },
  { code: "CZ", name: "Czech", locale: "cs" },
  { code: "SL", name: "Slovenian", locale: "sl" },
  { code: "SK", name: "Slovak", locale: "sk" },
  { code: "LT", name: "Lithuanian", locale: "lt" },
  { code: "ET", name: "Estonian", locale: "et" },
  { code: "RO", name: "Romanian", locale: "ro" },
  { code: "AL", name: "Albanian", locale: "sq" },
  { code: "CA", name: "Catalan", locale: "ca" },
  {
    code: "BR",
    name: "Brazilian Portuguese",
    locale: "pt-BR",
  },
  {
    code: "CA",
    name: "Canadian French",
    locale: "fr-CA",
  },
  {
    code: "AR",
    name: "Argentine Spanish",
    locale: "es-AR",
  },
  {
    code: "MX",
    name: "Mexican Spanish",
    locale: "es-MX",
  },
  {
    code: "VE",
    name: "Venezuelan Spanish",
    locale: "es-VE",
  },
  {
    code: "CO",
    name: "Colombian Spanish",
    locale: "es-CO",
  },
  {
    code: "CU",
    name: "Cuban Spanish",
    locale: "es-CU",
  },
  {
    code: "CL",
    name: "Chilean Spanish",
    locale: "es-CL",
  },
];
